### ISSUE TITLE
Example just shows a black box

### ISSUE THREAD

**Issue by Asherehsa** [cattsmall/Phaser-game#1]
http://cattsmall.github.io/Phaser-game/ just shows a black box for me. I'm not sure if this is the intended functionality.

**Comment by cattsmall** [comment]
That is intended! If you look at the console, you will notice that the game states are working. For an example game, please check the other branches (they don't have a GitHub Page).

**Comment by Asherehsa** [comment]
I did notice that but didn't think to look at the branches, thanks!
